# Generated by Django 4.1.13 on 2024-03-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_to_scrape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes_to_scrape.author'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(blank=True, to='quotes_to_scrape.tag'),
        ),
    ]
