# Generated by Django 4.1.13 on 2024-03-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_to_scrape', '0002_alter_author_born_location_alter_author_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'managed': False},
        ),
    ]
