# Generated by Django 4.1.13 on 2024-03-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_to_scrape', '0003_alter_quote_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={},
        ),
    ]
