# Generated by Django 4.1.13 on 2024-05-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_to_scrape', '0004_alter_quote_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quote',
            table='quotes_to_scrape_quote',
        ),
    ]
